name: Main
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --D warnings

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Build Dependencies + Environment
      run: sudo apt-get install capnproto
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --features slow_tests
    - name: Run tests
      run: cargo test --verbose --features slow_tests
    - name: Format
      run: cargo fmt --check
